server:
  port: 9004
spring:
  application:
    name: replay-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 600MB
  jackson:
    time-zone: GMT+8
    date-format: 'yyyy-MM-dd HH:mm:ss'
  #    default-property-inclusion: non_null
front:
  cacheHours: 1
  reBuild: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info